### PR TITLE
lib: add collectFiles and collectFilesAt

### PR DESCRIPTION
**Pull request by Misterio77**
This is a lib function that recursively reads a directory, and returns them in the format expected by `files`/`symlinks`. This makes it possible to, for example, link all mods from a modpack, and still include additional mods.

### CODE REVIEW

**Comment by Misterio77** [comment]
An example on how it works:

```
nix-repl> lib.collectFilesAt modpack "config"
{
  "config/appliedenergistics2/common.json" = "/nix/store/ihsw8ifdmv7xjd3v1c7zqbfbbqkqvzar-packwiz-pack-0.2.18//config/appliedenergistics2/common.json";
  "config/bclib/main.json" = "/nix/store/ihsw8ifdmv7xjd3v1c7zqbfbbqkqvzar-packwiz-pack-0.2.18//config/bclib/main.json";
  "config/bclib/server.json" = "/nix/store/ihsw8ifdmv7xjd3v1c7zqbfbbqkqvzar-packwiz-pack-0.2.18//config/bclib/server.json";
  "config/byg/biomepedia.json5" = "/nix/store/ihsw8ifdmv7xjd3v1c7zqbfbbqkqvzar-packwiz-pack-0.2.18//config/byg/biomepedia.json5";
  "config/byg/client/biomepedia_inventory.json5" = "/nix/store/ihsw8ifdmv7xjd3v1c7zqbfbbqkqvzar-packwiz-pack-0.2.18//config/byg/client/biomepedia_inventory.json5";
  "config/charm.toml" = "/nix/store/ihsw8ifdmv7xjd3v1c7zqbfbbqkqvzar-packwiz-pack-0.2.18//config/charm.toml";
    # ...
}
```

**Comment by Infinidoge** [comment]
Would it be good to have `collectFiles <path>`, with `collectFilesAt <path> <subdir>` being something like (in pseudo-code) `addPrefixToAttrKeys subdir (collectFiles "${path}/${subdir}")`?

If `files` / `symlinks` let you do something like
```nix
files = {
  config = {
    "file1" = ...;
    "file2" = ...;
  };
};
```
to create
```
config/file1
config/file2
```
Then `collectFiles` would be quite useful, but as it stands the system doesn't do that that, so I'm not really sure what cases where you'd need `collectFiles` on its own, unless you want to do `addPrefix "config" (collectFiles ./config)` instead of `collectFilesAt . "config"`

**Comment by Misterio77** [comment]
Hey! Sorry for taking so long to respond.

> Would it be good to have collectFiles <path>, with collectFilesAt <path> <subdir> being something like (in pseudo-code) addPrefixToAttrKeys subdir (collectFiles "${path}/${subdir}")?

This is a very good idea and looks cleaner, will def get that in.

> If files / symlinks let you do something like

This sounds super nice and actually kinda solves some concerns with composability, I think.

--- 

Sadly my current design for this PR has a major footgun.

We currently cleanup files when shutting down the server, but removing files/symlinks entries from your nixos config will NOT remove the files (as the service isn't stopped with the previous generation's stop script)! This isn't a major concern when using a single derivation for a big-ish directory, for example:
```nix
  services.minecraft-servers.servers.cool-modpack = {
    enable = true;
    package = pkgs.fabricServers.fabric-1_18_2-0_14_9;
    symlinks =  "${modpack}/mods"
};
```
Removing mods from `modpack` will propagate these changes to your server. The server might not cleanup the `mods`, but this isn't a problem as an empty directory does nothing on its own.

Once the entry is a leaf, that is, a single file, things get messy. As mentioned, the stop script will remove what's _currently_ defined, not what was _previously_ there. We'll have to special case this somehow. A few solutions I thought of:
- Keep track of managed files. Maybe a hidden file on the server root dir?
- Clean up more agressively. Always delete symlinks to nix store, or try and detect what is being managed some other way.

**Comment by Misterio77** [comment]
SMH, for every common problem, there is already an elegant solution haha, had no idea about that. Will look into it.

**Comment by Misterio77** [comment]
I think stopIfChanged is pretty limited (e.g. it won't work if we prefer to reload instead), so I decided to implement a file-attrs based solution (#116). With that merged, I plan on finishing this one.

**Comment by Misterio77** [comment]
Should be good to go.

**Review by Infinidoge — APPROVED** [review]

**Pull request merged**
